### ISSUE TITLE
Neovim support

### ISSUE THREAD

**Issue by pbower** [ubaldot/vim-replica#8]
Hi there

Looks awesome. Any chance of a Neovim version?

It doesn't seem to pull up properly given the Vim 9 stuff.

Thanks heaps

**Comment by ubaldot** [comment]
Hi! No, unfortunately I cannot code in Lua nor in legacy Vim, so I don't plan to port it to Neovim. Perhaps someone could fork it and make a Neovim version, but I really cannot do it. Sorry!
